### ISSUE TITLE
Note regarding binary-identical requirement of state-reproducibility tests

### ISSUE THREAD

**Issue by SamWindell** [free-audio/clap-validator#17]
This is more a point of reference rather than an issue, but I wanted to make note of it on this repo in case other have this too.

With the state-reproducibility tests, clap-validator validates that the blobs of binary data from your state save()/load() are identical, byte-for-byte. This is actually an additional requirement that a plugin needs to take account of. So long as the plugin reliably interprets the blobs correctly that is enough. But the additional binary-identical requirement that clap-validator enforces is a reasonable addition for better testing ability.

In my case, my plugin is storing little-endian binary data. A C++ struct like this example `struct { u8 a; u32 b; }` was being binary copied (`memcpy`) into the state blob. But there's an an important consideration here: there are 3 bytes of padding between the `u8 a` and `u32 b`. These 3 bytes are not necessarily zero; it depends on how the struct is initialised (detailed in the C++ standard [dcl.init]). In my case, these unused padding bytes happened to be different and so the state-reproducibility tests were failing. This was an unusual one to track down. The solution for me is more care regarding how binary data is stored - a worthwhile change to make for other reasons too.

**Comment by robbert-vdh** [comment]
There should eventually also be an extension or something that you can use to disable specific tests for a plugin, especially more pedantic ones like this (in addition to explicitly filtering them out on the command line invocation like you can now). I think this lint is still pretty important because more often than not this test failing is the result of a bug, but I can also understand that not every plugin wants to or can satisfy this requirement.

I'll close this issue since it's not actionable, but thanks for posting this!

**Comment by SamWindell** [comment]
Agreed, a filter to separate tests would be great as you suggest. One filter level for things that 100% of clap plugins should pass. And another level for pedantic tests that are very useful for catching bugs but might add small additional requirements to a plugin - like state-reproducibility.
