### ISSUE TITLE
Where does the validator search plugins for?

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap-validator#6]
I'm trying to build and install my plugins to `/usr/local/lib/clap`.

The REAPER DAW sees my plugins but does not instantiate.

I'm trying to use the `clap-validator` but have no idea about the place the plugins should be located for it because `./clap-validator list` gives nothing.

It could be nice to have a command line option to specify the plugin installation directory to force the validator to scan this directory.

**Comment by robbert-vdh** [comment]
Check the documentation from  `entry.h` for information on CLAP's standard plugin search paths and the `CLAP_PATH` environment variable: https://github.com/free-audio/clap/blob/main/include/clap/entry.h#L12-L29

You'll probably want to have it validate specific plugins though. The `clap-validator list` command is there mostly just because, and to serve as yet another reference implementation. See `clap-validator validate --help` for more all available options. The readme should probably list though (though running `clap-validator` will tell you about `clap-validator validate`).

**Comment by sadko4u** [comment]
Thanks. `CLAP_PATH` worked.
